---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "MoCa QR Voting System"
keywords:    "moca_qr, evoting, electronic voting, voting system, casting correctness"
description: "A Modular, Cast-as-intended Voter-Verifiable –QR code based– Electronic Voting System"
source_link: "https://github.com/CamiloG/moca_qr"
favicon:     "img/qr.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  dark-purple: '#542437'
